import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect, useRef } from "react";
import { useRouter } from "next/router";
export default function Home() {
  const router = useRouter();
  const userName = useRef(null);
  const password = useRef(null);

  const submitHandler = (e) => {
    e.preventDefault();
    console.log(userName.current.value);
    console.log(password.current.value);

    if (
      userName.current.value === "ADMIN" &&
      password.current.value === "ADMIN"
    ) {
      console.log("Login Successful");
      localStorage.setItem("admin", true);
      router.push("/dashboard");
    }
    if (
      userName.current.value === "USER1" &&
      password.current.value === "111"
    ) {
      localStorage.setItem("user", 1);
      localStorage.setItem("admin", false);
      router.push("/user");
    }
    if (
      userName.current.value === "USER2" &&
      password.current.value === "222"
    ) {
      localStorage.setItem("user", 2);
      localStorage.setItem("admin", false);
      router.push("/user");
    }
    if (
      userName.current.value === "USER3" &&
      password.current.value === "333"
    ) {
      localStorage.setItem("user", 3);
      localStorage.setItem("admin", false);
      router.push("/user");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Smart Medicine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="o-enter-container">
          <div classnName="o-enter-content">
            <h1>Sesión de administrativo</h1>
            <p className="o-enter-p">
              Descubre como se encuentra su planta conociendo su temperatura,
              humedad y si necesita que se lleve de la bomba de agua.
            </p>
            <button type="button">
              <a href="#miModal">Abrir Modal</a>
            </button>
          </div>
        </section>
        <section class="o-enter-user">
          <h1>Sesión de usuarios</h1>
          <p className="o-enter-p">
            Descubre como se encuentra su planta conociendo su temperatura,
            humedad y si necesita que se lleve de la bomba de agua.
          </p>
          <button type="button">
            <a href="#miModal">Abrir Modal</a>
          </button>
        </section>
      </main>
      <div id="miModal" className="modal">
        <div className="modal-contenido">
          <a href="#">X</a>

          <h1>Login</h1>
          <form onSubmit={submitHandler}>
            <label>
              Username:
              <input ref={userName} type="text" name="username" required />
            </label>
            <label>
              Password:
              <input ref={password} type="password" name="password" required />
            </label>
            <input type="submit" value="Login" />
          </form>
        </div>
      </div>
    </div>
  );
}
